### ISSUE TITLE
Verbal ingest requires refinements

### ISSUE THREAD

**Issue by jrwdunham** [dativebase/dailp-ingest-clj#5]
## TODOs

- [x] Complete ingestion of core DF1975 and DF2003 datasets.
  - [x] DF1975
  - [x] DF2003
  - Some lack translations, though adding these is a lower priority.
- [ ] Ingest other Feeling datasets (e.g., nouns and adjectives)
- [x] Add speakers
   - All forms from Feeling datasets are attributable to Durbin Feeling:
     dialect: Oklahoma Cherokee (OK). Proposal: speaker value "Feeling, Durbin",
     tag with name "Dialect: OK".
   - [x] in DF1975 verbs
   - [x] in DF2003 verbs
- [x] Move cross-references/citations from comments field to tags, e.g.:
   - Source: DF1975: 167
   - Source: DF2003: 223-224
   - [x] in DF1975 verbs
   - [x] in DF2003 verbs
- [x] Add sources to verb forms
   - [x] in DF1975 verbs
   - [x] in DF2003 verbs

## Lower Priority TODOs

- [x] Change S-categorized inflected verbs to category VP
- [x] Add textual sources (e.g., DF2003) [from previous ingest iteration](https://github.com/dativebase/dailp-ingest/blob/master/ingest/ingest.py#L1283-L1326) ([Google Sheet draft](https://docs.google.com/spreadsheets/d/1W46XymhtohAizs_KVRCNvfTUL0k4-LWwYbEv8aHau_4/edit#gid=0))
  - [x] DF1975 source resource exists?
  - [x] DF1975 associated to DF1975 forms?
  - [x] DF2003 source resource exists?
  - [x] DF2003 associated to DF2003 forms?

- [ ] Fix the "(with MID)"-translated V forms. For example, we should have both of the following:

      mb: /nu:'the:y/
      mg: twist(T)
      tl: twist (transitive)

      mb: /ata-nu:'the:y/
      mg: twist(T)
      tl: (with MID) twist (intransitive)

- [ ] Find the "projected" verb roots and pass their spreadsheet rows on to Jeff. These are the rows with only a "Transitivity" value where the other V (root) values are presumed to come from the preceding row.

- [x] Create a speaker for Durbin Feeling, who is both the author of DF1975 and DF2003 and the speaker to be attributed for the data therein.

- [ ] Create an example text collection.

## Maybes

- [ ] Create tags for dialects. Not doing this for now. Forms can be queried by dialect by filtering based on the dialect string value of the associated speaker. Discuss with Jeff to see if this is sufficient. Possible dialect tags:
  - dialect:oklahoma
  - dialect:north-carolina-1
  - dialect:north-carolina-2
  - dialect:lower-dialect (No known living speakers)
- [ ] Potentially implement a "citation" resource in the OLD. See [Issue 31](https://github.com/dativebase/dativebase/issues/31).
- [ ] Potentially implement some level of synchronization between OLD instances and Google Sheets.

## Retracted TODOs

- [ ] Add UUID columns with generated UUID values to all source spreadsheets
  - implement GSheet->Dative synchronization for the ingest script: If the GSheet is updated, then re-running the ingest script should update the UUID-identified OLD form instead of creating a new one.

**Comment by jrwdunham** [comment]
## Create UUID Columns in Cloned Spreadsheets

- [ ] DF1975--Master. ALL DONE.

  - original:
    DF1975--Master
    https://docs.google.com/spreadsheets/d/11ssqdimOQc_hp3Zk8Y55m6DFfKR96OOpclUg5wcGSVE/edit?usp=sharing
  - with UUIDS:
    DF1975--Master with UUIDs
    https://docs.google.com/spreadsheets/d/13cLK8rmu7bw4b5u3xMl28ZUFwmymrNXJAhM_BB7sFkg/edit?usp=sharing

- [ ] DAILP Tags. CLONING DONE.

  - original:
    DAILP Tags
    https://docs.google.com/spreadsheets/d/1eEk3JP2WTkP8BBShBHURrripKPredy-sCutQMiGfVmo/edit?usp=sharing
  - with UUIDS:
    DAILP Tags with UUIDs
    https://docs.google.com/spreadsheets/d/1b8eLC1K7j1O46moXt-4TjLshbXDmIjPGmoDSZb2m0kU/edit?usp=sharing

- [ ] Orthographic Inventories. CLONING DONE.

  - original:
    Orthographic Inventories
    https://docs.google.com/spreadsheets/d/16Dfq04tCSP0kuqBdMX1R3DHJ7kB6RJ3Uy7-ufN-Y_w8/edit?usp=sharing
  - with UUIDS:
    Orthographic Inventories with UUIDs
    https://docs.google.com/spreadsheets/d/15NP8jFGmGRjyA6DHrgah_CaYBXtg_NGk9N--zBAfUNA/edit?usp=sharing

- [ ] Syntactic Categories. CLONING DONE.

  - original:
    DAILP Syntactic Categories
    https://docs.google.com/spreadsheets/d/159i_Cygdqsnp55QBzqJu7eozxsNEiVIiXhwEzls3q7g/edit?usp=sharing
  - with UUIDS:
    DAILP Syntactic Categories with UUIDs
    https://docs.google.com/spreadsheets/d/1W5KxRsb4lRLDE1gz1XLlVylZ8AwbsajSWiYuIeozlJw/edit?usp=sharing

- [ ] Prepronominal Prefixes. CLONING DONE.

  - original:
    Prepronominal Prefixes
    https://docs.google.com/spreadsheets/d/12v5fqtOztwwLeEaKQJGMfziwlxP4n60riMsN9dYw9Xc/edit#gid=0
  - with UUIDS:
    Prepronominal Prefixes with UUIDs
    https://docs.google.com/spreadsheets/d/1ePxbt7AarhgmqwHDOsyqlK_Tm9xtzmWABCclAwd5P68/edit?usp=sharing

- [ ] Pronominal Prefixes, Combined.

  - original:
    https://docs.google.com/spreadsheets/d/1OMzkbDGY1BqPR_ZwJRe4-F5_I12Ao5OJqqMp8Ej_ZhE/edit?usp=sharing
  - with UUIDS:

- [ ] Pronominal Prefixes, Sets A & B.

  - original:
    https://docs.google.com/spreadsheets/d/1D0JZEwE-dj-fKppbosaGhT7Xyyy4lVxmgG02tpEi8nw/edit?usp=sharing
  - with UUIDS:

- [ ] Pronominal Prefixes, Reflexive & Middle.

  - original:
    https://docs.google.com/spreadsheets/d/1Q_q_1MZbmZ-g0bmj1sQouFFDnLBINGT3fzthPgqgkqo/edit?usp=sharing
  - with UUIDS:

- [ ] Modal Suffixes.

  - original:
    https://docs.google.com/spreadsheets/d/1QWYWFeK6xy7zciIliizeW2hBfuRPNk6dK5rGJf2pdNc/edit#gid=0
  - with UUIDS:

- [ ] Aspectual Suffixes.

  - original:
    https://docs.google.com/spreadsheets/d/19jPHtphsvWDliWq9z3WL_Fz6omHCFTFseD6fh1FLY70/edit#gid=0
  - with UUIDS:

- [ ] DF2003--Master

  - original:
    DF2003--Master
    https://docs.google.com/spreadsheets/d/18cKXgsfmVhRZ2ud8Cd7YDSHexs1ODHo6fkTPrmnwI1g/edit?usp=sharing
  - with UUIDS:
    DF2003--Master with UUIDs
    https://docs.google.com/spreadsheets/d/1VMedwTNNig1p9VgvH03zUUngPK9ldRnmt6XB4DWPWwM/edit?usp=sharing
